apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipv6-flusher
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipv6-flusher
  template:
    metadata:
      labels:
        app: ipv6-flusher
    spec:
      serviceAccountName: ipv6-flusher
      containers:
      - name: ipv6-flusher
        image: ghcr.io/log-z/k3s-ipv6-flusher:v{{ .Chart.Version }}
        imagePullPolicy: IfNotPresent
        env:
          - name: TZ
            value: {{ .Values.timezone }}
